### ISSUE TITLE
Can you share the source code and build process?

### ISSUE THREAD

**Issue by dougg0k** [e9k/ReyonMouseFix#1]
Hi,

Besides the title, are you able to share why and what do you make the API call for? Can you include the source code in the repository? @numlck 

I think if this was rewritten in Rust with much better clarity to everything, would be a very good addition to the community.

At least bindings for the intercept lib is already available. https://github.com/bozbez/interception-sys/ https://docs.rs/interception/latest/interception/

**Comment by SheMelody** [comment]
FYI Source code was not shared in the repo.
